/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "covrhuxggocuabshstbl"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvdnJodXhnZ29jdWFic2hzdGJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE3MTg3MTksImV4cCI6MjA3NzI5NDcxOX0.roJ-ABgJ6wzBMlvc1KIcJ1sQtYml8yX9qcOh4f1yRWg"
